CLASS zcl_11_log_c367_jrz DEFINITION INHERITING FROM zcl_10_log_c367_jrz
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
    get_private RETURNING VALUE(rv_attribute) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_11_LOG_C367_JRZ IMPLEMENTATION.


  METHOD get_private.


  ENDMETHOD.
ENDCLASS.
