CLASS zcl_14_log_c367_jrz DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS:
    airplane_type ABSTRACT RETURNING VALUE(rv_airplane_type) type string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_14_log_c367_jrz IMPLEMENTATION.
ENDCLASS.
