CLASS zcl_08_log_c367_jrz DEFINITION INHERITING FROM zcl_05_log_c367_jrz
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_08_LOG_C367_JRZ IMPLEMENTATION.
ENDCLASS.
