CLASS zcl_07_lion_log_c367_jrz DEFINITION
  PUBLIC
  INHERITING FROM zcl_06_animal_log_c367_jrz
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
        walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_07_LION_LOG_C367_JRZ IMPLEMENTATION.


  METHOD walk.
    rv_walk = 'The lion walks'.
  ENDMETHOD.
ENDCLASS.
