CLASS zcl_09_log_c367_jrz DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
    GLOBAL FRIENDS zcl_10_log_c367_jrz.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA: capital TYPE STRING.
ENDCLASS.



CLASS ZCL_09_LOG_C367_JRZ IMPLEMENTATION.
ENDCLASS.
