CLASS zcl_15_log_c367_jrz DEFINITION INHERITING FROM zcl_14_log_c367_jrz
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: airplane_type REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_15_log_c367_jrz IMPLEMENTATION.
  METHOD airplane_type.
    rv_airplane_type = 'tipo'.
  ENDMETHOD.

ENDCLASS.
